name: sync-to-wiki

on: push

jobs:
  sync:
    name: Sync to wiki
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: config
      run: |
        git config --global user.email "dogmatixed@gmail.com"
        git config --global user.name "Wiki Sync"
    - name: add remote
      run: git remote add wiki https://${{ github.token }}@github.com/${{ github.repository }}.wiki
    - name: fetch
      run: git fetch wiki
    - name: checkout wiki
      run: git checkout -b wiki-master wiki/master
    - name: merge
      run: git merge origin/master
    - name: push
      run: git push wiki wiki-master:master

